DESCRIPTIVES VARIABLES=Yaş İş_Tatmini Tükenmişlik Özyeterlik
  /STATISTICS=MEAN STDDEV SKEWNESS KURTOSIS MIN MAX.

CORRELATIONS /VARIABLES=Yaş İş_Tatmini Tükenmişlik Özyeterlik
  /PRINT=TWOTAIL SIG
  /MISSING=PAIRWISE.

T-TEST GROUPS=Cinsiyet
  /VARIABLES=Yaş
  /CRITERIA=CI(.95).

REGRESSION /DEPENDENT Özyeterlik
  /METHOD=ENTER Yaş İş_Tatmini Tükenmişlik
  /STATISTICS COEFF OUTS R ANOVA COLLIN TOL.
